"""empty message

Revision ID: 092fd877b323
Revises: 2b24307cc483
Create Date: 2021-10-28 13:07:59.963241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092fd877b323'
down_revision = '2b24307cc483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=100), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
