"""empty message

Revision ID: 0e7beedfec05
Revises: 0c92e3ba7a2c
Create Date: 2021-10-26 14:11:54.590845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e7beedfec05'
down_revision = '0c92e3ba7a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_list')
    op.drop_table('serie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('youtube_url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_list',
    sa.Column('serie_id', sa.INTEGER(), nullable=True),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], )
    )
    # ### end Alembic commands ###
