"""empty message

Revision ID: 19ee1f819e10
Revises: 5cfe5cc4b690
Create Date: 2021-10-25 14:39:02.371789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ee1f819e10'
down_revision = '5cfe5cc4b690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_genres',
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.Column('series_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    # ### end Alembic commands ###
