"""empty message

Revision ID: 27839a28e57d
Revises: ec04877bc16d
Create Date: 2021-12-26 00:27:53.988825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27839a28e57d'
down_revision = 'ec04877bc16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime_min', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('runtime_min')

    # ### end Alembic commands ###
