"""empty message

Revision ID: 3dccc1e26173
Revises: 4c6c3e4a1863
Create Date: 2021-10-26 15:28:50.643159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dccc1e26173'
down_revision = '4c6c3e4a1863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_name'), ['name'], unique=True)

    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_director_name'), ['name'], unique=True)

    op.create_table('series_actors',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.create_table('series_directors',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_directors')
    op.drop_table('series_actors')
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_director_name'))

    op.drop_table('director')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_name'))

    op.drop_table('actor')
    # ### end Alembic commands ###
