"""empty message

Revision ID: 4503bb9ecfd8
Revises: 2c0cf1a1b417
Create Date: 2021-11-28 23:07:43.240888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4503bb9ecfd8'
down_revision = '2c0cf1a1b417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_studio',
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_studio')
    # ### end Alembic commands ###
