"""empty message

Revision ID: 4c6c3e4a1863
Revises: ac15b41e3e9c
Create Date: 2021-10-26 15:18:38.745969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6c3e4a1863'
down_revision = 'ac15b41e3e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('published_year')

    # ### end Alembic commands ###
