"""empty message

Revision ID: 5cfe5cc4b690
Revises: 20812356341e
Create Date: 2021-10-25 14:28:48.479819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfe5cc4b690'
down_revision = '20812356341e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_name', sa.String(length=100), nullable=True))
        batch_op.drop_column('season')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.INTEGER(), nullable=True))
        batch_op.drop_column('season_name')

    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
