"""empty message

Revision ID: 673abeb2d467
Revises: 0e7beedfec05
Create Date: 2021-10-26 15:09:43.362056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673abeb2d467'
down_revision = '0e7beedfec05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
