"""empty message

Revision ID: 6c13f43e6e94
Revises: 7a9bff234c75
Create Date: 2021-11-06 14:16:31.742163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c13f43e6e94'
down_revision = '7a9bff234c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_list',
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.drop_table('series_seasons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series_seasons',
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.Column('series_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.drop_table('season_list')
    # ### end Alembic commands ###
