"""empty message

Revision ID: a5923a1c126a
Revises: e4b1c6dbd3f9
Create Date: 2021-10-26 13:58:03.580036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5923a1c126a'
down_revision = 'e4b1c6dbd3f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serie')
    with op.batch_alter_table('episode_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('episode_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'episode', ['episode_id'], ['id'])
        batch_op.drop_column('serie_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serie_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'serie', ['serie_id'], ['id'])
        batch_op.drop_column('episode_id')

    op.create_table('serie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('youtube_url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
