"""empty message

Revision ID: b268bfb7db5a
Revises: edacb6300236
Create Date: 2021-10-25 22:22:01.730868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b268bfb7db5a'
down_revision = 'edacb6300236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
