"""empty message

Revision ID: c33bbb6ce6cb
Revises: e45621cfac8e
Create Date: 2021-10-28 11:12:05.589511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33bbb6ce6cb'
down_revision = 'e45621cfac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actor_name'), ['name'], unique=True)

    op.create_table('director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_director_name'), ['name'], unique=True)

    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('youtube_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_list',
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], )
    )
    op.create_table('movie_actors',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('movie_directors',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], )
    )
    op.create_table('series_actors',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.create_table('series_directors',
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.create_table('series_genres',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.drop_table('season_genres')
    op.drop_table('serie')
    op.drop_table('series_list')
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('yt_playlist_url', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('published_year', sa.Integer(), nullable=True))
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('yt_playlist_url')
        batch_op.drop_column('season_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('yt_playlist_url', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('published_year')
        batch_op.drop_column('yt_playlist_url')
        batch_op.drop_column('season_title')

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)

    op.create_table('series_list',
    sa.Column('serie_id', sa.INTEGER(), nullable=True),
    sa.Column('series_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.create_table('serie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('youtube_url', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season_genres',
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], )
    )
    op.drop_table('series_genres')
    op.drop_table('series_directors')
    op.drop_table('series_actors')
    op.drop_table('movie_directors')
    op.drop_table('movie_actors')
    op.drop_table('episode_list')
    op.drop_table('episode')
    with op.batch_alter_table('director', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_director_name'))

    op.drop_table('director')
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actor_name'))

    op.drop_table('actor')
    # ### end Alembic commands ###
