"""empty message

Revision ID: db2ae9cbd83e
Revises: 
Create Date: 2021-10-08 10:45:22.728565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2ae9cbd83e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
