"""empty message

Revision ID: dbd18b7f4023
Revises: db2ae9cbd83e
Create Date: 2021-10-08 11:10:52.977375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd18b7f4023'
down_revision = 'db2ae9cbd83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('image', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
