"""empty message

Revision ID: e4707ce4f24c
Revises: be9c8b8d9cdf
Create Date: 2021-11-06 22:14:55.180180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4707ce4f24c'
down_revision = 'be9c8b8d9cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tvshow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('thumbnail', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tvshow_actors',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('tvshow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['tvshow_id'], ['tvshow.id'], )
    )
    op.create_table('tvshow_genres',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('tvshow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['tvshow_id'], ['tvshow.id'], )
    )
    op.create_table('tvshow_season',
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('tvshow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['tvshow_id'], ['tvshow.id'], )
    )
    op.drop_table('tv_show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tv_show',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('thumbnail', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tvshow_season')
    op.drop_table('tvshow_genres')
    op.drop_table('tvshow_actors')
    op.drop_table('tvshow')
    # ### end Alembic commands ###
