"""empty message

Revision ID: e4b1c6dbd3f9
Revises: 905bac1c71f0
Create Date: 2021-10-26 13:56:34.225836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b1c6dbd3f9'
down_revision = '905bac1c71f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_genres')
    op.drop_table('series_list')
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('yt_playlist_url', sa.String(length=100), nullable=False))
        batch_op.drop_column('title')
        batch_op.drop_column('description')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_column('yt_playlist_url')
        batch_op.drop_column('season_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_title', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('yt_playlist_url', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('yt_playlist_url')
        batch_op.drop_column('season_title')

    op.create_table('series_list',
    sa.Column('serie_id', sa.INTEGER(), nullable=True),
    sa.Column('series_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], )
    )
    op.create_table('season_genres',
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.Column('season_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], )
    )
    # ### end Alembic commands ###
