"""empty message

Revision ID: ec04877bc16d
Revises: dd9d31e789ca
Create Date: 2021-12-03 00:28:01.363363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec04877bc16d'
down_revision = 'dd9d31e789ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=True))

    with op.batch_alter_table('tvshow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tvshow', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
