"""empty message

Revision ID: ed2f927bd868
Revises: 4503bb9ecfd8
Create Date: 2021-12-02 15:55:23.155418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2f927bd868'
down_revision = '4503bb9ecfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_studio',
    sa.Column('studio_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_studio')
    # ### end Alembic commands ###
