"""empty message

Revision ID: edacb6300236
Revises: 19ee1f819e10
Create Date: 2021-10-25 22:16:32.922559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edacb6300236'
down_revision = '19ee1f819e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_title', sa.String(length=100), nullable=False))
        batch_op.drop_column('season_name')
        batch_op.drop_column('last_updated')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('season_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('season_title')

    # ### end Alembic commands ###
